public class Dummy {
/*
//Create an Account for a contact if there isn't an account already related
//

public class ContactAccountCreate {
  /*  //get contact info
    @invocablemethod
    public static void createAccounts(){
        
    list<Contact> contList = [SELECT FirstName, LastName, AccountId FROM Contact WHERE AccountId = null];
    list<Account> acctList = new list<Account>();    
    //create new accounts for contacts without accounts.
    Account acc = new Account();
    
    for(Contact con : contList){
        acc.Name = con.FirstName + ' ' + con.LastName;
        con.AccountId = acc.Id;
        acctList.add(acc);
        system.debug(acctList);
       }
        insert acctList;
    }

}*/
}